api_platform:
    title: Book manager
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/BookStore/Domain/Model'
            - '%kernel.project_dir%/src/Security/Domain/Model'
    defaults:
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        use_symfony_listeners: true
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
